name:
  certis

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-certis-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: certis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - certis
    volumes:
      - postgres-certis-volume:/data/postgres
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=root1234
    command: server /data --console-address ":9001"
    volumes:
      - minio-certis-volume:/data
    networks:
      - certis

networks:
  certis:
    driver: bridge
volumes:
  postgres-certis-volume:
  minio-certis-volume:
